name: Build Windows (fork)

on:
  push:
    branches: [compress-export]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 60
    steps:
      # Windows fix. See https://github.com/actions/checkout/issues/226
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - run: yarn install --immutable --network-timeout 1000000

      - run: yarn download-ffmpeg-win32-x64

      - run: yarn build

      - run: yarn electron-builder --publish never --win 7z --x64

      - uses: actions/upload-artifact@v4
        with:
          name: LosslessCut-win-x64
          path: dist/win-unpacked
